#! /bin/sh
### BEGIN INIT INFO
# Provides:          lcd server
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     1
# Default-Stop:
# Short-Description: lcd server start and stop script
### END INIT INFO

export HOME
case "$1" in
	start)
		echo "Starting LCD"
		python /root/WS/LCD/LCD.py 2>&1 &
	;;
	stop)
		echo "Stopping LCD"
		LCD_PID=`ps aux | grep LCD.py | head -1 | awk '{print $2}'`
		sudo kill -9 $LCD_PID
	;;
	*)
		echo "Usage: /etc/init.d/lcd {start|stop}"
		exit 1
	;;
esac
exit 0